### ISSUE TITLE
Can not skip `DROP PROCEDURE` with schema-pattern

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/ticdc#3360]
### What did you do?

```
use db;
/*!*/ DROP PROCEDURE `xxx`
```

```
filters:
  filter-rule-1:
    schema-pattern: "db"
    events: [".*\\s+DROP\\s+PROCEDURE"]
    action: Ignore
```

### What did you expect to see?

no error occurs

### What did you see instead?

```
"result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 36067,
                                "ErrClass": "sync-unit",
                                "ErrScope": "internal",
                                "ErrLevel": "high",
                                "Message": "startLocation: [position: (mysql-bin.000001, 1849), gtid-set: ], endLocation: [position: (mysql-bin.000001, 1970), gtid-set: ], origin SQL: [/*!*/ DROP PROCEDURE IF EXISTS `xxx`]: parse DDL: /*!*/ DROP PROCEDURE IF EXISTS `xxx`",
                                "RawCause": "line 1 column 20 near \"PROCEDURE IF EXISTS `xxx`\" ",
                                "Workaround": "Please confirm your DDL statement is correct and needed. For TiDB compatible DDL, see https://docs.pingcap.com/tidb/stable/mysql-compatibility#ddl. You can use `handle-error` command to skip or replace the DDL or add a binlog filter rule to ignore it if the DDL is not needed."
                            }
                        ],
                        "detail": null
                    },
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
with an all schema pattern, the event was skipped correctly.
```
filters:
  filter-rule-1:
    schema-pattern: "*"
    events: [".*\\s+DROP\\s+PROCEDURE"]
    action: Ignore
```
