### ISSUE TITLE
cdc cli don't work normally.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/ticdc#3627]
### What did you do?

ticdc.toml
```toml
 [security]
   ca-path = "$TLS_DIR/ca.pem"
   cert-path = "$TLS_DIR/server.pem"
   key-path = "$TLS_DIR/server-key.pem"
```
start cdc server with tls config aboved and does not use `--cert-allowed-cn` flag to specific client cert's common name:
```
run_cdc_server \
		--workdir $WORK_DIR \
		--binary $CDC_BINARY \
		--logsuffix "_${TEST_NAME}_tls1" \
		--pd "https://${TLS_PD_HOST}:${TLS_PD_PORT}" \
		--addr "127.0.0.1:8300" \
		--config "$WORK_DIR/ticdc.toml" \
		--tlsdir "$TLS_DIR" \
```

### What did you expect to see?

cli likes below work well. 
```
cdc cli changefeed list --pd "https://127.0.0.1:2379" --ca\="/_certificates/ca.pem" --cert="/_certificates/client.pem" --key="/client-key.pem" 
```

### What did you see instead?

it return an tls connection related error.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.3.0
```

TiCDC version (execute `cdc version`):

```console
v5.3.0
```
